name:                liveview-simple
version:             0.1.0.0
github:              "ewilden/liveview-simple"
license:             Apache
author:              "Evan Wildenhain"
maintainer:          "evan.wildenhain@gmail.com"
copyright:           "2021 Google LLC"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ewilden/liveview-simple#readme>

dependencies:
- base >= 4.7 && < 5
- Diff >= 0.3.4 && < 1
- aeson >= 1.5.5.1 && < 2
# - aeson-diff >= 1.1.0.7 && < 2
- aeson-qq >= 0.8.3 && < 1
- algebraic-graphs
- async
- bytestring
- composition >= 1.0.2.1 && < 2
- cookie
- extra >= 1.6.17 && < 2
# - generic-lens
- focus
- hashable >= 1.3.0.0 && < 2
- hedgehog >= 1.0.4 && < 2
- http-api-data
- http-types
- jose
- lens
- lens-aeson
- list-t
- lucid >= 2.9.11 && < 3
- MonadRandom
- monoidal-containers
- mtl >= 2.2.2 && < 3
- neat-interpolation
- profunctors
- random
- reducers
- semigroupoids
- servant
- servant-auth
- servant-auth-server
- servant-lucid
- servant-server
- servant-websockets
- stm
- stm-containers
- streaming
- text >= 1.2.3.1 && < 2
- transformers-base
- tuple
- unliftio
- unordered-containers >= 0.2.13.0 && < 1
- vector >= 0.12.1.2 && < 1
- wai
- wai-websockets
- warp
- websockets

ghc-options:
- -fwarn-incomplete-patterns
- -Werror

default-extensions: 
# GHC 2021
- EmptyCase
- PostfixOperators
- TupleSections
- ImportQualifiedPost
- NamedFieldPuns
- BangPatterns
- BinaryLiterals
- HexFloatLiterals
- NumericUnderscores
- GADTSyntax
- RankNTypes
- TypeApplications
- PolyKinds
- StandaloneKindSignatures
- ExistentialQuantification
- TypeOperators
- ConstraintKinds
- ExplicitForAll
- KindSignatures
- NamedWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- ConstrainedClassMethods
- InstanceSigs
- TypeSynonymInstances
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- StandaloneDeriving
- EmptyDataDeriving
- DeriveLift
- GeneralisedNewtypeDeriving
- DeriveGeneric
# Others
- LambdaCase
- NamedFieldPuns
- TupleSections

library:
  source-dirs: src

executables:
  liveview-simple-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liveview-simple

tests:
  liveview-simple-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liveview-simple
